wallet:
  seeds_path: "data/seeds"
  default_password: "YOUR_PASS"

taostats:
  api_key: "YOUR_API_KEY"
  api_url: "https://api.taostats.io/api"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/bittensor_manager.log"

registration:
  default_prep_time: 15
  max_prep_time: 19

cache:
  ttl_seconds: 300         # Cache TTL for general data (5 minutes)
  price_ttl_seconds: 60    # Cache TTL for TAO price (1 minute)

stats:
  default_hide_zeros: false # By default show all neurons including zero balance
  parallel_requests: true   # Enable parallel requests
  max_concurrent_tasks: 10  # Maximum number of concurrent tasks
  export_enabled: false      # Enable export function
  auto_refresh: 0           # Auto refresh interval in seconds (0 = disabled)
